$ANSIBLE_VAULT;1.1;AES256
65323832353063376531313836663063623063323737626465383230303731363631636364333838
6262333664653865303636346633343137323034383132360a303663323566333637366161323563
32393137393230653530333136303264623437306663393861366565633936643931633561613832
3464313831343935340a343934373635643231663334383537373465376538316534636335313266
61366131626237346135356463666132303934313336323064643362356165626461616362326163
65363363633630363966616334346265346666343333313339383030393937356537356135323237
62663936633137303231386434623161643630656664656564363435616137363361366131333734
37383336326332663830333531303132383362636166656363363235373534353236373231353066
31366535326564373536616535323636303365616563363538343061626531643434
